In [2]:
from torch.autograd import Variable
import torch as t
#使用Tensor新建Variable
x = Variable(t.ones(2, 2), requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [4]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [5]:
# grad在反向传递过程中是累加的，这要求每次反向传播前将梯度清零
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [6]:
#清零梯度
x.grad.data.zero_()
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [8]:
#Variable和Tensor具有近乎一致的接口,可切换使用
x = Variable(t.ones(4,5))
y = t.cos(x)
x_tensor_cos = t.cos(x.data)
print(y)
x_tensor_cos

tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])


tensor([[0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403],
        [0.5403, 0.5403, 0.5403, 0.5403, 0.5403]])